"""Meta-label signal filter model (M05-01).

Contract: Automatic base-strategy decisions and outcomes -> TAKE/SKIP probability.

Guarantees:
1. M05-01-AC0: Train meta-model on base-strategy outcomes; predict returns TAKE probability in [0, 1].
2. M05-01-AC1: Manual clicks/intents strictly forbidden as training labels (ManualLabelForbiddenError).
3. M05-01-AC2: Meta split purge base label overlap (temporal overlap between train and test purged).
4. M05-01-AC3: Compare base vs filtered strategy performance on identical candidate trades.
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from typing import Any

import numpy as np
import pandas as pd
from pydantic import BaseModel, ConfigDict, Field
from sklearn.ensemble import RandomForestClassifier


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class ManualLabelForbiddenError(ValueError):
    """Raised when manual click or human intent is provided as a training label."""


# ---------------------------------------------------------------------------
# Domain models
# ---------------------------------------------------------------------------


class MetaTradeSample(BaseModel):
    """A trade generated by the base strategy with associated features and outcome."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    trade_id: str
    entry_time: datetime
    exit_time: datetime
    features: dict[str, float]
    realized_return: float
    label: int = Field(description="1 if return > 0 (TAKE), 0 otherwise (SKIP)")
    is_manual: bool = False


class M05Config(BaseModel):
    """Configuration for M05 Meta-Label Signal Filter."""

    model_config = ConfigDict(frozen=True, extra="forbid", protected_namespaces=())

    model_id: str = "M05"
    version: str = "1.0.0"
    take_threshold: float = 0.50
    n_estimators: int = 50
    max_depth: int = 3
    seed: int = 42


class M05FittedBundle(BaseModel):
    """Immutable bundle containing metadata and hashes for fitted M05 meta-model."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    config: M05Config
    feature_names: list[str]
    bundle_hash: str
    fitted_at_utc: datetime = Field(default_factory=lambda: datetime.now(UTC))


class MetaFilterComparisonReport(BaseModel):
    """Comparison report between base strategy and meta-filtered strategy on same candidates."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    total_candidates: int
    base_trades_count: int
    filtered_trades_count: int
    base_win_rate: float
    filtered_win_rate: float
    base_mean_return: float
    filtered_mean_return: float


# ---------------------------------------------------------------------------
# Purge logic (M05-01-AC2)
# ---------------------------------------------------------------------------


def purge_overlapping_trades(
    reference_trades: list[MetaTradeSample],
    target_trades: list[MetaTradeSample],
) -> list[MetaTradeSample]:
    """Purge target trades whose holding period overlaps with any reference trade.

    Two trades overlap if:
        (target.entry_time < ref.exit_time) and (target.exit_time > ref.entry_time)

    Args:
        reference_trades: Trades defining the reference intervals (e.g. training set).
        target_trades: Trades to filter (e.g. test set).

    Returns:
        List of target trades that do NOT overlap with any reference trade.
    """
    clean_targets: list[MetaTradeSample] = []
    for tgt in target_trades:
        overlaps = False
        for ref in reference_trades:
            if (tgt.entry_time < ref.exit_time) and (tgt.exit_time > ref.entry_time):
                overlaps = True
                break
        if not overlaps:
            clean_targets.append(tgt)
    return clean_targets


# ---------------------------------------------------------------------------
# M05MetaLabelTrainer
# ---------------------------------------------------------------------------


class M05MetaLabelTrainer:
    """Trainer for secondary meta-model filtering primary strategy signals."""

    def __init__(self, config: M05Config) -> None:
        self.config = config
        self._clf: RandomForestClassifier | None = None
        self._bundle: M05FittedBundle | None = None

    @property
    def bundle(self) -> M05FittedBundle:
        if self._bundle is None:
            raise RuntimeError("M05MetaLabelTrainer is not fitted yet. Call train() first.")
        return self._bundle

    def train(self, trades: list[MetaTradeSample]) -> M05FittedBundle:
        """Fit the meta-label model on base-strategy outcomes (M05-01-AC0, AC1).

        Args:
            trades: List of ``MetaTradeSample`` records.

        Returns:
            An immutable ``M05FittedBundle``.

        Raises:
            ManualLabelForbiddenError: If any sample has ``is_manual=True`` (M05-01-AC1).
        """
        # AC1: Validate no manual clicks/intents are used as training labels
        for trade in trades:
            if trade.is_manual:
                raise ManualLabelForbiddenError(
                    f"MANUAL_CLICK_FORBIDDEN: Trade '{trade.trade_id}' is flagged as manual. "
                    "Manual clicks or human intent must not be used as meta-labels (M05-01-AC1)."
                )

        if not trades:
            raise ValueError("NO_TRADES_PROVIDED: Cannot train meta-model on empty trade list.")

        # Canonical sorted feature names from the first trade
        feature_names = sorted(trades[0].features.keys())

        # Construct feature matrix and labels
        X_rows = [[trade.features.get(f, 0.0) for f in feature_names] for trade in trades]
        y_rows = [trade.label for trade in trades]

        X = np.array(X_rows, dtype=np.float64)
        y = np.array(y_rows, dtype=np.int64)

        clf = RandomForestClassifier(
            n_estimators=self.config.n_estimators,
            max_depth=self.config.max_depth,
            random_state=self.config.seed,
            n_jobs=1,
        )
        clf.fit(X, y)
        self._clf = clf

        # Deterministic bundle hash
        hash_payload = {
            "config": self.config.model_dump(mode="json"),
            "feature_names": feature_names,
            "classes": [int(c) for c in clf.classes_],
        }
        raw_hash = json.dumps(hash_payload, sort_keys=True).encode("utf-8")
        bundle_hash = hashlib.sha256(raw_hash).hexdigest()

        self._bundle = M05FittedBundle(
            config=self.config,
            feature_names=feature_names,
            bundle_hash=bundle_hash,
        )
        return self._bundle

    def predict_take_proba(self, trades: list[MetaTradeSample]) -> np.ndarray:
        """Predict TAKE probability for each candidate trade (M05-01-AC0).

        Args:
            trades: List of candidate trades.

        Returns:
            1-D numpy array of probabilities for class 1 (TAKE).
        """
        if self._clf is None or self._bundle is None:
            raise RuntimeError("M05MetaLabelTrainer is not fitted yet. Call train() first.")

        if not trades:
            return np.empty((0,), dtype=np.float64)

        X_rows = [[trade.features.get(f, 0.0) for f in self._bundle.feature_names] for trade in trades]
        X = np.array(X_rows, dtype=np.float64)

        proba = self._clf.predict_proba(X)
        classes = list(self._clf.classes_)

        # Return probability of TAKE (label=1)
        if 1 in classes:
            take_idx = classes.index(1)
            return proba[:, take_idx]
        else:
            return np.zeros(len(trades), dtype=np.float64)

    def compare_base_vs_filtered(
        self,
        candidate_trades: list[MetaTradeSample],
    ) -> MetaFilterComparisonReport:
        """Compare base-strategy vs meta-filtered strategy on identical candidates (M05-01-AC3).

        Args:
            candidate_trades: List of candidate trades generated by the base strategy.

        Returns:
            A ``MetaFilterComparisonReport``.
        """
        if not candidate_trades:
            return MetaFilterComparisonReport(
                total_candidates=0,
                base_trades_count=0,
                filtered_trades_count=0,
                base_win_rate=0.0,
                filtered_win_rate=0.0,
                base_mean_return=0.0,
                filtered_mean_return=0.0,
            )

        probas = self.predict_take_proba(candidate_trades)
        base_returns = np.array([t.realized_return for t in candidate_trades])

        # Filtered trades: where TAKE probability meets or exceeds threshold
        take_mask = probas >= self.config.take_threshold
        filtered_returns = base_returns[take_mask]

        base_win_rate = float(np.mean(base_returns > 0)) if len(base_returns) > 0 else 0.0
        base_mean_ret = float(np.mean(base_returns)) if len(base_returns) > 0 else 0.0

        filtered_win_rate = float(np.mean(filtered_returns > 0)) if len(filtered_returns) > 0 else 0.0
        filtered_mean_ret = float(np.mean(filtered_returns)) if len(filtered_returns) > 0 else 0.0

        return MetaFilterComparisonReport(
            total_candidates=len(candidate_trades),
            base_trades_count=len(candidate_trades),
            filtered_trades_count=int(np.sum(take_mask)),
            base_win_rate=base_win_rate,
            filtered_win_rate=filtered_win_rate,
            base_mean_return=base_mean_ret,
            filtered_mean_return=filtered_mean_ret,
        )
