"""Forward paper trading and shadow portfolio management (SHADOW-01, SHADOW-02)."""

from indodax_lab.paper.contracts import (
    DuplicateDecisionError,
    ForwardDecision,
    ForwardDecisionRecord,
    ForwardDecisionStatus,
    ManualIntentRecord,
    ModelMismatchError,
    PaperDecisionStore,
    RejectedDecision,
    StaleDataError,
)
from indodax_lab.paper.portfolio import (
    CheckpointIntegrityError,
    InsufficientCashError,
    IntentProcessingResult,
    MaxPositionsExceededError,
    PaperOrderIntent,
    PaperPosition,
    SharedCapitalLedger,
    SharedLedgerCheckpoint,
)
from indodax_lab.paper.promotion import (
    ChallengerEvidence,
    ChampionRegistry,
    InsufficientForwardDurationError,
    InsufficientForwardTradesError,
    InsufficientQualityPromotionError,
    MissingPromotionApprovalError,
    NoPromotedChampionError,
    PolicyBreachPromotionError,
    PromotionApproval,
    PromotionDecision,
    SelfApprovedPromotionError,
    StalePromotionEvidenceError,
    UnsealedCandidatePromotionError,
)
from indodax_lab.paper.tournament_service import (
    CohortManifest,
    CohortNotFoundError,
    CohortRecord,
    ComparisonMetricRow,
    ComparisonReport,
    DuplicateCandidateCohortError,
    IncomparableCohortError,
    Leaderboard,
    LeaderboardExcludedRow,
    LeaderboardRankRow,
    QualificationDecision,
    SubjectPolicyInfo,
    TournamentError,
    TournamentService,
)

__all__ = [
    # SHADOW-01
    "DuplicateDecisionError",
    "ForwardDecision",
    "ForwardDecisionRecord",
    "ForwardDecisionStatus",
    "ManualIntentRecord",
    "ModelMismatchError",
    "PaperDecisionStore",
    "RejectedDecision",
    "StaleDataError",
    # SHADOW-02
    "CheckpointIntegrityError",
    "InsufficientCashError",
    "IntentProcessingResult",
    "MaxPositionsExceededError",
    "PaperOrderIntent",
    "PaperPosition",
    "SharedCapitalLedger",
    "SharedLedgerCheckpoint",
    # SHADOW-03
    "ChallengerEvidence",
    "ChampionRegistry",
    "InsufficientForwardDurationError",
    "InsufficientForwardTradesError",
    "InsufficientQualityPromotionError",
    "MissingPromotionApprovalError",
    "NoPromotedChampionError",
    "PolicyBreachPromotionError",
    "PromotionApproval",
    "PromotionDecision",
    "SelfApprovedPromotionError",
    "StalePromotionEvidenceError",
    "UnsealedCandidatePromotionError",
    # RW5-02
    "CohortManifest",
    "CohortNotFoundError",
    "CohortRecord",
    "ComparisonMetricRow",
    "ComparisonReport",
    "DuplicateCandidateCohortError",
    "IncomparableCohortError",
    "Leaderboard",
    "LeaderboardExcludedRow",
    "LeaderboardRankRow",
    "QualificationDecision",
    "SubjectPolicyInfo",
    "TournamentError",
    "TournamentService",
]
